### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by stereodenis** [doomsower/react-native-yandexmapkit#1]
![rnyandexmap h 2016-10-19 15-10-56](https://cloud.githubusercontent.com/assets/1406461/19518164/5ec6e3ba-960e-11e6-88bc-28a328859627.png)

**Comment by doomsower** [comment]
What version of react-native are you using? Are you able to build example project?

**Comment by stereodenis** [comment]
@doomsower forgot to add to Podfile
```
# Pods for example
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'RCTGeolocation'
  ]
```

**Comment by stereodenis** [comment]
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: String.prototype.es6
  Paths: /Users/stereodenis/work/evrone/one_button/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/String.prototype.es6.js collides with /Users/stereodenis/work/evrone/one_button/ios/Pods/React/packager/react-packager/src/DependencyResolver/polyfills/String.prototype.es6.js

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: String.prototype.es6
  Paths: /Users/stereodenis/work/evrone/one_button/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/String.prototype.es6.js collides with /Users/stereodenis/work/evrone/one_button/ios/Pods/React/packager/react-packager/src/DependencyResolver/polyfills/String.prototype.es6.js

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/stereodenis/work/evrone/one_button/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:155:13)
    at module.getName.then.name (/Users/stereodenis/work/evrone/one_button/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:115:31)

**Comment by doomsower** [comment]
Seems that pod installer copied some js files into ios/Pods/React directory, and because of this packager has naming collision. 
This does not happen for me. What versions of react-native and cocoapods are you using? Try to clean node_modules and pods and do a fresh install.

**Comment by stereodenis** [comment]
cleaning Pods directory fixes this
