### ISSUE TITLE
Can't load tiles

### ISSUE THREAD

**Issue by stereodenis** [doomsower/react-native-yandexmapkit#2]
What should I add to Info.plist
Now I have
```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			...
			<key>yandex.net</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

**Comment by doomsower** [comment]
I just tried this config and it works for me. However, when I removed all ATS keys from Info.plist, in Instruments I saw a request to `yandex.ru` subdomain, maybe adding it to exceptions will solve the problem?

**Comment by stereodenis** [comment]
@doomsower 
I add 
```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```
but got this 
![iphone 5 ios 10 1 14b72 2016-11-03 17-43-35](https://cloud.githubusercontent.com/assets/1406461/19970466/16dbe240-a1ed-11e6-8f42-dea6f0521836.png)

**Comment by doomsower** [comment]
Ok, are you sure you're passing YMK API key before you mount react component?

**Comment by stereodenis** [comment]
@doomsower yes, I'm sure

**Comment by doomsower** [comment]
I'm running out of ideas. Does your project work on Android device (not emulator)? Can you make example project work with you API key?

**Comment by stereodenis** [comment]
@doomsower checking on android and ios simulators. I will check on real devices

**Comment by stereodenis** [comment]
@doomsower same result on real device

**Comment by doomsower** [comment]
What about example project?

**Comment by stereodenis** [comment]
@doomsower ok, i'll make example project

**Comment by stereodenis** [comment]
@doomsower https://github.com/stereodenis/yandexMapkitExample

**Comment by stereodenis** [comment]
@doomsower I missunderstand map api key and mapkit api key
